/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DayaBeliRouteImport } from './routes/daya-beli'
import { Route as LaporRouteImport } from './routes/lapor'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as TrenRouteImport } from './routes/tren'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DayaBeliRoute = DayaBeliRouteImport.update({
  id: '/daya-beli',
  path: '/daya-beli',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporRoute = LaporRouteImport.update({
  id: '/lapor',
  path: '/lapor',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const TrenRoute = TrenRouteImport.update({
  id: '/tren',
  path: '/tren',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daya-beli': typeof DayaBeliRoute
  '/lapor': typeof LaporRoute
  '/laporan': typeof LaporanRoute
  '/tren': typeof TrenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daya-beli': typeof DayaBeliRoute
  '/lapor': typeof LaporRoute
  '/laporan': typeof LaporanRoute
  '/tren': typeof TrenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daya-beli': typeof DayaBeliRoute
  '/lapor': typeof LaporRoute
  '/laporan': typeof LaporanRoute
  '/tren': typeof TrenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/daya-beli' | '/lapor' | '/laporan' | '/tren'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/daya-beli' | '/lapor' | '/laporan' | '/tren'
  id:
    '__root__' | '/' | '/admin' | '/daya-beli' | '/lapor' | '/laporan' | '/tren'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DayaBeliRoute: typeof DayaBeliRoute
  LaporRoute: typeof LaporRoute
  LaporanRoute: typeof LaporanRoute
  TrenRoute: typeof TrenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daya-beli': {
      id: '/daya-beli'
      path: '/daya-beli'
      fullPath: '/daya-beli'
      preLoaderRoute: typeof DayaBeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lapor': {
      id: '/lapor'
      path: '/lapor'
      fullPath: '/lapor'
      preLoaderRoute: typeof LaporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tren': {
      id: '/tren'
      path: '/tren'
      fullPath: '/tren'
      preLoaderRoute: typeof TrenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DayaBeliRoute: DayaBeliRoute,
  LaporRoute: LaporRoute,
  LaporanRoute: LaporanRoute,
  TrenRoute: TrenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
