/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrenRouteImport } from './routes/tren'
import { Route as ApiSnapshotRouteImport } from './routes/api/snapshot'
import { Route as ApiTrendRouteImport } from './routes/api/trend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrenRoute = TrenRouteImport.update({
  id: '/tren',
  path: '/tren',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSnapshotRoute = ApiSnapshotRouteImport.update({
  id: '/api/snapshot',
  path: '/api/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendRoute = ApiTrendRouteImport.update({
  id: '/api/trend',
  path: '/api/trend',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tren': typeof TrenRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/trend': typeof ApiTrendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tren': typeof TrenRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/trend': typeof ApiTrendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tren': typeof TrenRoute
  '/api/snapshot': typeof ApiSnapshotRoute
  '/api/trend': typeof ApiTrendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tren' | '/api/snapshot' | '/api/trend'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tren' | '/api/snapshot' | '/api/trend'
  id: '__root__' | '/' | '/tren' | '/api/snapshot' | '/api/trend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrenRoute: typeof TrenRoute
  ApiSnapshotRoute: typeof ApiSnapshotRoute
  ApiTrendRoute: typeof ApiTrendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tren': {
      id: '/tren'
      path: '/tren'
      fullPath: '/tren'
      preLoaderRoute: typeof TrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/snapshot': {
      id: '/api/snapshot'
      path: '/api/snapshot'
      fullPath: '/api/snapshot'
      preLoaderRoute: typeof ApiSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trend': {
      id: '/api/trend'
      path: '/api/trend'
      fullPath: '/api/trend'
      preLoaderRoute: typeof ApiTrendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrenRoute: TrenRoute,
  ApiSnapshotRoute: ApiSnapshotRoute,
  ApiTrendRoute: ApiTrendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
